# Exported from Render on 2024-10-08T00:54:20Z
services:
- type: web
  name: NoteTakerAppforModule11
  runtime: node
  repo: https://github.com/sgforcert/NoteTakerAppforModule11
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: npm start
version: "1"
